"""Pine-Code Generator for LightGBM Tree Cascades (V1 FX-Modell, ANN-018).

Minimal — one entry point, no abstraction layers, no plug-in framework.

Usage in NB15c (Colab driver):
    from core.export.pine_codegen import (
        lgbm_to_pine_cascade,
        python_reimplementation,
        bit_exact_check,
    )

    booster = lgb.Booster(model_file='artifacts/models/fx_v1_lgbm_seed7.txt')
    feature_names = [...]   # exact order used at training time
    pine_snippet = lgbm_to_pine_cascade(booster, feature_names)

    # Bit-exact validation BEFORE patching the Pine skeleton
    check = bit_exact_check(booster, feature_names, X_test, atol=1e-5)
    assert check['passed'], check
"""
from __future__ import annotations

import math
from typing import Any, Iterable

import numpy as np


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def lgbm_to_pine_cascade(booster, feature_names: list[str]) -> str:
    """Render a LightGBM booster as a Pine v6 nested-if-else cascade.

    Returns a Pine snippet that defines a single function
    `f_pace_algo_v1_probability(...)` taking 27 feature inputs in the order
    of `feature_names`. The function returns a float in [0, 1] (sigmoid of
    sum of tree raw scores).

    Pine output format (one variable per tree, summed at the end):
        f_pace_algo_v1_probability(f_hour_sin, f_atr_pct, ...) =>
            t_0 = (f_hour_sin <= 0.5) ? ((f_atr_pct <= 1.2) ? -0.1 : 0.05) : ...
            t_1 = ...
            ...
            raw = t_0 + t_1 + ... + t_29
            1.0 / (1.0 + math.exp(-raw))

    The LightGBM binary classifier uses `<= threshold → left, > threshold → right`
    (or `default_left` for missings — we assume features are NaN-free as in
    the pipeline).
    """
    model_dict = booster.dump_model()
    trees = model_dict['tree_info']

    # Sanity: the booster must reference only known features
    _validate_features(trees, feature_names)

    lines: list[str] = []
    lines.append("// === Generated by core/export/pine_codegen.py ===")
    lines.append("// DO NOT EDIT — regenerate via notebooks/15c_v1_pine_export.ipynb")
    lines.append(f"// Source booster: {len(trees)} trees, {len(feature_names)} features")
    lines.append("")

    arglist = ", ".join(_pine_arg(name) for name in feature_names)
    lines.append(f"f_pace_algo_v1_probability({arglist}) =>")
    indent = "    "

    tree_vars: list[str] = []
    for tree_idx, tree_info in enumerate(trees):
        var = f"t_{tree_idx}"
        expr = _tree_to_pine_expr(tree_info['tree_structure'], feature_names)
        lines.append(f"{indent}{var} = {expr}")
        tree_vars.append(var)

    raw_expr = " + ".join(tree_vars)
    lines.append(f"{indent}raw = {raw_expr}")
    lines.append(f"{indent}1.0 / (1.0 + math.exp(-raw))")

    return "\n".join(lines) + "\n"


def python_reimplementation(booster, feature_names: list[str],
                              X: np.ndarray) -> np.ndarray:
    """Mirror of the generated Pine cascade — used for bit-exact validation.

    Walks the same tree structure with the same `<= threshold` decision rule
    and returns the same sigmoid-of-sum-of-leaves output. If this matches the
    LightGBM booster's own predict() output, the Pine snippet (which is a
    transliteration of this function) is also numerically faithful.
    """
    model_dict = booster.dump_model()
    trees = model_dict['tree_info']
    if X.ndim != 2 or X.shape[1] != len(feature_names):
        raise ValueError(
            f"X shape mismatch: expected (N, {len(feature_names)}), got {X.shape}"
        )

    n = X.shape[0]
    raw_scores = np.zeros(n, dtype=np.float64)
    for tree_info in trees:
        root = tree_info['tree_structure']
        for i in range(n):
            raw_scores[i] += _eval_tree(root, X[i])
    # Sigmoid
    return 1.0 / (1.0 + np.exp(-raw_scores))


def extract_feature_usage(booster, feature_names: list[str]) -> dict:
    """Inspect a booster and report which features it actually splits on.

    Returns a dict with:
      - 'used_features': list of feature_name (in deterministic split-count order)
      - 'unused_features': list of feature_name with zero splits
      - 'details': list of per-feature stats sorted by split_count desc:
            [{feature_name, feature_idx, split_count, used_in_tree_count,
              total_gain, avg_gain}]
      - 'n_trees': total trees in the booster
      - 'n_features_referenced': len(used_features)
    """
    model_dict = booster.dump_model()
    trees = model_dict['tree_info']
    n_trees = len(trees)
    n_features = len(feature_names)

    split_count = [0] * n_features
    used_in_tree = [0] * n_features
    total_gain = [0.0] * n_features

    for tree_info in trees:
        per_tree_seen: set[int] = set()
        _accumulate(tree_info['tree_structure'],
                     split_count, total_gain, per_tree_seen)
        for idx in per_tree_seen:
            used_in_tree[idx] += 1

    details = []
    for idx, name in enumerate(feature_names):
        details.append({
            'feature_name':       name,
            'feature_idx':        idx,
            'split_count':        split_count[idx],
            'used_in_tree_count': used_in_tree[idx],
            'total_gain':         total_gain[idx],
            'avg_gain':           (total_gain[idx] / split_count[idx]) if split_count[idx] > 0 else 0.0,
        })
    details.sort(key=lambda d: (-d['split_count'], d['feature_name']))

    used = [d['feature_name'] for d in details if d['split_count'] > 0]
    unused = [d['feature_name'] for d in details if d['split_count'] == 0]

    return {
        'n_trees':                n_trees,
        'n_features_referenced':  len(used),
        'used_features':          used,
        'unused_features':        unused,
        'details':                details,
    }


def _accumulate(node: dict,
                  split_count: list[int],
                  total_gain: list[float],
                  per_tree_seen: set) -> None:
    if 'leaf_value' in node:
        return
    feat_idx = int(node['split_feature'])
    split_count[feat_idx] += 1
    total_gain[feat_idx] += float(node.get('split_gain', 0.0))
    per_tree_seen.add(feat_idx)
    if 'left_child' in node:
        _accumulate(node['left_child'], split_count, total_gain, per_tree_seen)
    if 'right_child' in node:
        _accumulate(node['right_child'], split_count, total_gain, per_tree_seen)


def estimate_pine_ops(pine_code: str,
                       pine_budget_per_bar: int = 5000,
                       request_security_budget: int = 40) -> dict:
    """Heuristic Pine budget estimate.

    Counts:
      - approximate ops/bar from operator density + ternary depth
      - request.security() calls (hard limit 40 in Pine v6)
      - total file size (bytes + lines)

    Warnings flagged when any usage exceeds 70% of the relevant budget.
    Heuristic only — Pine compiler is the source of truth in TradingView.
    """
    # Operator-density heuristic: each binary operator + each ternary branch
    # roughly costs one op/bar. ta.* calls cost more (~5 ops each — they are
    # incremental indicators backed by Pine's internal state).
    # This is intentionally conservative — better to flag a warning early
    # than to miss a Pine compiler "ops exceeded" failure in TradingView.
    op_chars = sum(pine_code.count(c) for c in ['+', '-', '*', '/', '?', '<', '>', '='])
    ta_calls = pine_code.count('ta.')
    math_calls = pine_code.count('math.')
    request_security_calls = pine_code.count('request.security(')
    nz_calls = pine_code.count('nz(')

    # Heuristic weights — calibrated against typical Pine v6 tree-cascades.
    # Tree splits (`<= ? :`) are highly optimized by Pine compiler, so the
    # per-op_char weight is low. The dominant costs are ta.* (incremental
    # indicators with internal state) and request.security wrappers.
    # IMPORTANT: this is a CONSERVATIVE proxy — the source of truth is
    # TradingView's own "Compile" ops counter at paste time.
    ops_estimate = int(
        0.5 * op_chars + 8 * ta_calls + 2 * math_calls
        + 10 * request_security_calls + nz_calls
    )

    n_lines = pine_code.count('\n') + 1
    n_bytes = len(pine_code.encode('utf-8'))

    ops_pct = ops_estimate / pine_budget_per_bar if pine_budget_per_bar > 0 else 0.0
    rs_pct = request_security_calls / request_security_budget if request_security_budget > 0 else 0.0

    warnings = []
    if ops_pct > 0.70:
        warnings.append(
            f"ops/bar ~{ops_estimate} = {ops_pct:.0%} of budget {pine_budget_per_bar} (>70%)"
        )
    if rs_pct > 0.70:
        warnings.append(
            f"request.security calls = {request_security_calls} = {rs_pct:.0%} of budget {request_security_budget} (>70%)"
        )

    return {
        'ops_estimate':                 ops_estimate,
        'ops_pct_of_budget':            ops_pct,
        'pine_budget_per_bar':          pine_budget_per_bar,
        'request_security_calls':       request_security_calls,
        'request_security_pct_of_budget': rs_pct,
        'request_security_budget':      request_security_budget,
        'n_lines':                      n_lines,
        'n_bytes':                      n_bytes,
        'ta_calls':                     ta_calls,
        'math_calls':                   math_calls,
        'nz_calls':                     nz_calls,
        'op_chars':                     op_chars,
        'warnings':                     warnings,
        'passed_budget_check':          len(warnings) == 0,
    }


def bit_exact_check(booster, feature_names: list[str],
                      X: np.ndarray, atol: float = 1e-5) -> dict:
    """Compare booster.predict(X) vs python_reimplementation(X).

    Returns dict with passed (bool), max_abs_diff (float), rmse (float),
    and per-sample diagnostics if failed.
    """
    expected = booster.predict(X)
    actual = python_reimplementation(booster, feature_names, X)
    diff = np.abs(expected - actual)
    max_abs = float(diff.max()) if len(diff) > 0 else 0.0
    rmse = float(np.sqrt((diff ** 2).mean())) if len(diff) > 0 else 0.0
    passed = max_abs <= atol
    out = {
        'passed':       passed,
        'atol':         atol,
        'n_samples':    int(X.shape[0]),
        'max_abs_diff': max_abs,
        'rmse':         rmse,
    }
    if not passed:
        worst = int(np.argmax(diff))
        out['worst_sample_idx'] = worst
        out['worst_expected'] = float(expected[worst])
        out['worst_actual'] = float(actual[worst])
        out['worst_diff'] = float(diff[worst])
    return out


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_PINE_INVALID_CHARS = str.maketrans('', '', '.-')


def _pine_arg(feature_name: str) -> str:
    """Stable Pine-safe argument name (collisionless prefix)."""
    # Pine identifiers: letters/digits/underscore, must start with letter.
    safe = feature_name.translate(_PINE_INVALID_CHARS)
    return f"f_{safe}"


def _validate_features(trees: list[dict], feature_names: list[str]) -> None:
    """Confirm every split_feature index referenced by the booster is within
    bounds of the provided feature_names list."""
    n = len(feature_names)
    referenced = _collect_feature_indices(trees)
    out_of_range = [i for i in referenced if i < 0 or i >= n]
    if out_of_range:
        raise ValueError(
            f"Booster references feature indices {sorted(set(out_of_range))} "
            f"but only {n} feature names were provided."
        )


def _collect_feature_indices(trees: list[dict]) -> set[int]:
    found: set[int] = set()

    def walk(node: dict) -> None:
        if 'leaf_value' in node:
            return
        if 'split_feature' in node:
            found.add(int(node['split_feature']))
        if 'left_child' in node:
            walk(node['left_child'])
        if 'right_child' in node:
            walk(node['right_child'])

    for tree_info in trees:
        walk(tree_info['tree_structure'])
    return found


def _tree_to_pine_expr(node: dict, feature_names: list[str]) -> str:
    """Recursively render a LightGBM tree node as a Pine ternary expression.

    Decision rule: LightGBM default is `feature <= threshold → left_child,
    > threshold → right_child` for numerical splits with `decision_type='<='`.
    We assume features are clean (no NaN) — matches our pipeline contract.
    """
    if 'leaf_value' in node:
        return _format_float(node['leaf_value'])

    feat_idx = int(node['split_feature'])
    threshold = float(node['threshold'])
    decision = node.get('decision_type', '<=')
    if decision != '<=':
        # LightGBM also emits '==' for categorical splits. We don't expect
        # any categoricals in the V1 feature set — fail loudly if encountered.
        raise NotImplementedError(
            f"Unsupported decision_type {decision!r} at node — feature {feat_idx}. "
            f"V1 pipeline expects numerical-only splits."
        )

    arg = _pine_arg(feature_names[feat_idx])
    th = _format_float(threshold)
    left = _tree_to_pine_expr(node['left_child'], feature_names)
    right = _tree_to_pine_expr(node['right_child'], feature_names)
    return f"({arg} <= {th} ? {left} : {right})"


def _eval_tree(node: dict, fv: np.ndarray) -> float:
    """Walk a LightGBM tree the same way the generated Pine cascade does.

    Decision rule mirrors `_tree_to_pine_expr` exactly: numerical `<= threshold`
    sends to left_child, otherwise right_child. Leaf nodes return leaf_value.
    """
    while True:
        if 'leaf_value' in node:
            return float(node['leaf_value'])
        feat_idx = int(node['split_feature'])
        threshold = float(node['threshold'])
        decision = node.get('decision_type', '<=')
        if decision != '<=':
            raise NotImplementedError(
                f"Unsupported decision_type {decision!r} during eval — "
                f"V1 pipeline expects numerical-only splits."
            )
        node = node['left_child'] if fv[feat_idx] <= threshold else node['right_child']


def _format_float(value: float) -> str:
    """Stable Pine-compatible float literal.

    We keep 12 significant digits so the Pine-side cast to float64 is
    bit-identical to Python's representation for typical LightGBM
    leaf_value / threshold magnitudes.
    """
    f = float(value)
    if math.isnan(f) or math.isinf(f):
        raise ValueError(f"Non-finite tree node value: {value}")
    # repr() gives Python's round-trip-safe shortest representation.
    return repr(f)
