"""Pine-Code Generator for LightGBM Tree Cascades (V1 FX-Modell, ANN-018).

Minimal — one entry point, no abstraction layers, no plug-in framework.

Usage in NB15c (Colab driver):
    from core.export.pine_codegen import (
        lgbm_to_pine_cascade,
        python_reimplementation,
        bit_exact_check,
    )

    booster = lgb.Booster(model_file='artifacts/models/fx_v1_lgbm_seed7.txt')
    feature_names = [...]   # exact order used at training time
    pine_snippet = lgbm_to_pine_cascade(booster, feature_names)

    # Bit-exact validation BEFORE patching the Pine skeleton
    check = bit_exact_check(booster, feature_names, X_test, atol=1e-5)
    assert check['passed'], check
"""
from __future__ import annotations

import math
from typing import Any, Iterable

import numpy as np


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def lgbm_to_pine_cascade(booster, feature_names: list[str]) -> str:
    """Render a LightGBM booster as a Pine v6 nested-if-else cascade.

    Returns a Pine snippet that defines a single function
    `f_pace_algo_v1_probability(...)` taking 27 feature inputs in the order
    of `feature_names`. The function returns a float in [0, 1] (sigmoid of
    sum of tree raw scores).

    Pine output format (one variable per tree, summed at the end):
        f_pace_algo_v1_probability(f_hour_sin, f_atr_pct, ...) =>
            t_0 = (f_hour_sin <= 0.5) ? ((f_atr_pct <= 1.2) ? -0.1 : 0.05) : ...
            t_1 = ...
            ...
            raw = t_0 + t_1 + ... + t_29
            1.0 / (1.0 + math.exp(-raw))

    The LightGBM binary classifier uses `<= threshold → left, > threshold → right`
    (or `default_left` for missings — we assume features are NaN-free as in
    the pipeline).
    """
    model_dict = booster.dump_model()
    trees = model_dict['tree_info']

    # Sanity: the booster must reference only known features
    _validate_features(trees, feature_names)

    lines: list[str] = []
    lines.append("// === Generated by core/export/pine_codegen.py ===")
    lines.append("// DO NOT EDIT — regenerate via notebooks/15c_v1_pine_export.ipynb")
    lines.append(f"// Source booster: {len(trees)} trees, {len(feature_names)} features")
    lines.append("")

    arglist = ", ".join(_pine_arg(name) for name in feature_names)
    lines.append(f"f_pace_algo_v1_probability({arglist}) =>")
    indent = "    "

    tree_vars: list[str] = []
    for tree_idx, tree_info in enumerate(trees):
        var = f"t_{tree_idx}"
        expr = _tree_to_pine_expr(tree_info['tree_structure'], feature_names)
        lines.append(f"{indent}{var} = {expr}")
        tree_vars.append(var)

    raw_expr = " + ".join(tree_vars)
    lines.append(f"{indent}raw = {raw_expr}")
    lines.append(f"{indent}1.0 / (1.0 + math.exp(-raw))")

    return "\n".join(lines) + "\n"


def python_reimplementation(booster, feature_names: list[str],
                              X: np.ndarray) -> np.ndarray:
    """Mirror of the generated Pine cascade — used for bit-exact validation.

    Walks the same tree structure with the same `<= threshold` decision rule
    and returns the same sigmoid-of-sum-of-leaves output. If this matches the
    LightGBM booster's own predict() output, the Pine snippet (which is a
    transliteration of this function) is also numerically faithful.
    """
    model_dict = booster.dump_model()
    trees = model_dict['tree_info']
    if X.ndim != 2 or X.shape[1] != len(feature_names):
        raise ValueError(
            f"X shape mismatch: expected (N, {len(feature_names)}), got {X.shape}"
        )

    n = X.shape[0]
    raw_scores = np.zeros(n, dtype=np.float64)
    for tree_info in trees:
        root = tree_info['tree_structure']
        for i in range(n):
            raw_scores[i] += _eval_tree(root, X[i])
    # Sigmoid
    return 1.0 / (1.0 + np.exp(-raw_scores))


def bit_exact_check(booster, feature_names: list[str],
                      X: np.ndarray, atol: float = 1e-5) -> dict:
    """Compare booster.predict(X) vs python_reimplementation(X).

    Returns dict with passed (bool), max_abs_diff (float), rmse (float),
    and per-sample diagnostics if failed.
    """
    expected = booster.predict(X)
    actual = python_reimplementation(booster, feature_names, X)
    diff = np.abs(expected - actual)
    max_abs = float(diff.max()) if len(diff) > 0 else 0.0
    rmse = float(np.sqrt((diff ** 2).mean())) if len(diff) > 0 else 0.0
    passed = max_abs <= atol
    out = {
        'passed':       passed,
        'atol':         atol,
        'n_samples':    int(X.shape[0]),
        'max_abs_diff': max_abs,
        'rmse':         rmse,
    }
    if not passed:
        worst = int(np.argmax(diff))
        out['worst_sample_idx'] = worst
        out['worst_expected'] = float(expected[worst])
        out['worst_actual'] = float(actual[worst])
        out['worst_diff'] = float(diff[worst])
    return out


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_PINE_INVALID_CHARS = str.maketrans('', '', '.-')


def _pine_arg(feature_name: str) -> str:
    """Stable Pine-safe argument name (collisionless prefix)."""
    # Pine identifiers: letters/digits/underscore, must start with letter.
    safe = feature_name.translate(_PINE_INVALID_CHARS)
    return f"f_{safe}"


def _validate_features(trees: list[dict], feature_names: list[str]) -> None:
    """Confirm every split_feature index referenced by the booster is within
    bounds of the provided feature_names list."""
    n = len(feature_names)
    referenced = _collect_feature_indices(trees)
    out_of_range = [i for i in referenced if i < 0 or i >= n]
    if out_of_range:
        raise ValueError(
            f"Booster references feature indices {sorted(set(out_of_range))} "
            f"but only {n} feature names were provided."
        )


def _collect_feature_indices(trees: list[dict]) -> set[int]:
    found: set[int] = set()

    def walk(node: dict) -> None:
        if 'leaf_value' in node:
            return
        if 'split_feature' in node:
            found.add(int(node['split_feature']))
        if 'left_child' in node:
            walk(node['left_child'])
        if 'right_child' in node:
            walk(node['right_child'])

    for tree_info in trees:
        walk(tree_info['tree_structure'])
    return found


def _tree_to_pine_expr(node: dict, feature_names: list[str]) -> str:
    """Recursively render a LightGBM tree node as a Pine ternary expression.

    Decision rule: LightGBM default is `feature <= threshold → left_child,
    > threshold → right_child` for numerical splits with `decision_type='<='`.
    We assume features are clean (no NaN) — matches our pipeline contract.
    """
    if 'leaf_value' in node:
        return _format_float(node['leaf_value'])

    feat_idx = int(node['split_feature'])
    threshold = float(node['threshold'])
    decision = node.get('decision_type', '<=')
    if decision != '<=':
        # LightGBM also emits '==' for categorical splits. We don't expect
        # any categoricals in the V1 feature set — fail loudly if encountered.
        raise NotImplementedError(
            f"Unsupported decision_type {decision!r} at node — feature {feat_idx}. "
            f"V1 pipeline expects numerical-only splits."
        )

    arg = _pine_arg(feature_names[feat_idx])
    th = _format_float(threshold)
    left = _tree_to_pine_expr(node['left_child'], feature_names)
    right = _tree_to_pine_expr(node['right_child'], feature_names)
    return f"({arg} <= {th} ? {left} : {right})"


def _eval_tree(node: dict, fv: np.ndarray) -> float:
    """Walk a LightGBM tree the same way the generated Pine cascade does.

    Decision rule mirrors `_tree_to_pine_expr` exactly: numerical `<= threshold`
    sends to left_child, otherwise right_child. Leaf nodes return leaf_value.
    """
    while True:
        if 'leaf_value' in node:
            return float(node['leaf_value'])
        feat_idx = int(node['split_feature'])
        threshold = float(node['threshold'])
        decision = node.get('decision_type', '<=')
        if decision != '<=':
            raise NotImplementedError(
                f"Unsupported decision_type {decision!r} during eval — "
                f"V1 pipeline expects numerical-only splits."
            )
        node = node['left_child'] if fv[feat_idx] <= threshold else node['right_child']


def _format_float(value: float) -> str:
    """Stable Pine-compatible float literal.

    We keep 12 significant digits so the Pine-side cast to float64 is
    bit-identical to Python's representation for typical LightGBM
    leaf_value / threshold magnitudes.
    """
    f = float(value)
    if math.isnan(f) or math.isinf(f):
        raise ValueError(f"Non-finite tree node value: {value}")
    # repr() gives Python's round-trip-safe shortest representation.
    return repr(f)
